name: Test Build

on:
  workflow_dispatch:
  # push:
  #   branches: [ main, master ]
  #   paths:
  #     - 'package.nix'
  #     - 'flake.nix'
  #     - 'module.nix'
  # pull_request:
  #   branches: [ main, master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build package
        run: |
          nix build .#ab-download-manager --show-trace || true
          echo "If build failed with hash mismatch, copy the correct hash from above logs"

  test-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Test Home Manager module
        run: |
          echo "Testing Home Manager module syntax..."
          nix eval .#homeManagerModules.default --show-trace
          echo "Home Manager module syntax is valid!"
